

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  project: default
  source:
    repoURL: 'https://github.com/aqeelakhtar/gitpractice.git'
    path: my-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
